name: Java Cl
on: [push]

jobs:
  build:
  
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        java: [10, 12, 14]
    steps:
      - uses: actions/checkout@v3
        

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setp-java@v3
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'

      - name: Build with Maven
      run: mvn -B package --file pom.xml
